function grad_dx = get_grad_dx(x_pred,x_train,alpha,kfcn_grad,query_format)
    grad_dx = cat(2,...
        kfcn_grad(x_pred,x_train,query_format,1)*alpha,...
        kfcn_grad(x_pred,x_train,query_format,2)*alpha);
end